//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public int VehiculoID { get; set; }
        public int ModeloID { get; set; }
        public int NumeroChasis { get; set; }
        public int NumeroCarroceria { get; set; }
        public string Patente { get; set; }
        public short NumeroPuertas { get; set; }
        public int Color { get; set; }
        public int Caja { get; set; }
        public decimal Cilindrada { get; set; }
        public int Tapizado { get; set; }
    
        public virtual Modelo Modelo { get; set; }
    }
}
