//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public int VehiculoID { get; set; }
        public int ModeloID { get; set; }
        public int NumeroChasis { get; set; }
        public int NumeroCarroceria { get; set; }
        public string Patente { get; set; }
        public short NumeroPuertas { get; set; }
        public int ColorID { get; set; }
        public int CajaID { get; set; }
        public decimal Cilindrada { get; set; }
        public int TapizadoID { get; set; }
    
        public virtual Caja Caja { get; set; }
        public virtual Color Color { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual Tapizado Tapizado { get; set; }
    }
}
